### ISSUE TITLE
FileBrowser is missing from most recent build

### ISSUE THREAD

**Issue by elliot-sawyer** [georgehanson/Vue-Form-Components#10]
Hello, great work on this component! I was trying to set up the FileBrowser component but noticed that it failed to load. Digging into the issue, I found that it's omitted in index.ts (https://github.com/GeorgeHanson/Vue-Form-Components/blob/master/src/index.ts#L4)

Given that it's fully documented and has tests, I wanted to check if there was a reason it was not included with the build? I'm working on a pull request but I'm having some issues compiling the project. 

Hopefully it's an easy fix!

**Comment by GeorgeHanson** [comment]
Hey, thanks for pointing this out :)

Off the top of my head, I can't think why this would have been omitted, must have been a mistake. Feel free to submit a PR for this

**Comment by georgehanson** [comment]
Issue resolved (6a07dfc)
