### ISSUE TITLE
Select List - initially selected option

### ISSUE THREAD

**Issue by pigeonmow** [georgehanson/Vue-Form-Components#13]
It's not clear from your documentation & I can't figure out how to pass the select list component the option to be selected when initially loaded?

**Comment by midnite81** [comment]
Yeah come on - up your game.

**Comment by georgehanson** [comment]
In your component make sure the `v-model` is the object you want the value to be.

For example:

```javascript
data() {
  return {
    selectListValue: {
       id: 1,
      label: 'My Option'
    },
    selectListOptions: [
      {
        id: 1,
        label: 'My Option',
      },
      {
        id: 2,
        label: 'Option 2'
      }
    ]
  }
}
```

And then your select list would look something like this

```html
<select-list :options="selectListOptions" v-model="selectListValue"></select-list>
```
