### ISSUE TITLE
Bootstrap version?

### ISSUE THREAD

**Issue by tomByrer** [GeorgeHanson/Vue-Form-Components#5]
I looked to see what version BS you use, but couldn't find info on it?
TIA :)

**Comment by GeorgeHanson** [comment]
This is for Bootstrap 3 - are you looking for a specific version of Bootstrap?

**Comment by tomByrer** [comment]
I've seen components & templates based on [BootStrap 4](https://v4-alpha.getbootstrap.com/migration/) already.
More of a documentation suggestion, though I would personally prefer to start building using v4 for flexbox & rem sizing.

**Comment by GeorgeHanson** [comment]
Update: @tomByrer This now uses Bootstrap 4
